### ISSUE TITLE
Exception starting 1.10.4 due to dotnet trimming

### ISSUE THREAD

**Issue by chrissimon-au** [dev-cycles/contextive#61]
**Describe the bug**

```
Unhandled exception. System.AggregateException: One or more errors occurred. (The type initializer for 'DryIoc.Registrator' threw an exception.)
 ---> System.TypeInitializationException: The type initializer for 'DryIoc.Registrator' threw an exception.
 ---> DryIoc.ContainerException: code: Error.UndefinedMethodWhenGettingTheSingleMethod;
message: Undefined Method '"Initializer"' in Type DryIoc.Registrator (including non-public=True)
   at DryIoc.Throw.ThrowIfNull[T](T, Int32 , Object , Object , Object , Object )
   at DryIoc.ReflectionTools.SingleMethod(Type, String, Boolean )
   at DryIoc.Registrator..cctor()
   --- End of inner exception stack trace ---
   at OmniSharp.Extensions.JsonRpc.JsonRpcServerServiceCollectionExtensions.AddJsonRpcMediatR(IContainer)
   at OmniSharp.Extensions.JsonRpc.JsonRpcServerServiceCollectionExtensions.AddJsonRpcServerCore[T](IContainer, JsonRpcServerOptionsBase`1)
   at OmniSharp.Extensions.LanguageServer.Shared.LanguageProtocolServiceCollectionExtensions.AddLanguageProtocolInternals[T](IContainer, LanguageProtocolRpcOptionsBase`1)
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServerServiceCollectionExtensions.AddLanguageServerInternals(IContainer, LanguageServerOptions, IServiceProvider )
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServer.From(LanguageServerOptions, IServiceProvider , CancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit() in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 454
   at Microsoft.FSharp.Control.AsyncPrimitives.QueueAsyncAndWaitForResultSynchronously[a](CancellationToken, FSharpAsync`1, FSharpOption`1) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 1140
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1, FSharpOption`1 , FSharpOption`1 ) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 1511
   at Contextive.LanguageServer.Program.main(String[]) in /home/runner/work/contextive/contextive/src/language-server/Contextive.LanguageServer/Program.fs:line 36
```

**To Reproduce**
Start contextive v1.10.4

**Expected behavior**
It should start normally.

**Desktop (please complete the following information):**
All

**Additional context**
From local testing, is caused by the use of https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-self-contained

**Comment by chrissimon-au** [comment]
A fix will be deployed with trimming turned off, but as it increases the binary size from 49MB to 106MB and the zip'd artifacts from 20MB to 42MB, this issue is used to track resolving properly and restoring trimming.

**Comment by chrissimon-au** [comment]
Almost certainly caused by the recent update to .net 7.0 and this [breaking change](https://learn.microsoft.com/en-us/dotnet/core/compatibility/deployment/7.0/trim-all-assemblies).

> Trimming now trims all assemblies in console apps, by default. This change only affects apps that are published with PublishTrimmed=true, and it only breaks apps that had existing trim warnings.

While we did have `PublishTrimmed=true` we didn't have trim warnings, so this doesn't seem accurate.

Experimenting with the official revert approach (`<TrimMode>partial</TrimMode>`) does allow to trim the output (smaller file size) without the exception.  This is likely the way forward.

However, what's curious is that the exception is specifically `Undefined Method '"Initializer"' in Type DryIoc.Registrator`.  In theory, we should be able to mark the `DryIoc` dependency (`DryIoc.Internal`?) as a TrimmerRoot to prevent trimming of anything within that assembly.  However, when attempting to do that, it fails saying the assembly cannot be found. Of note, the dependency is marked as [PrivateAssets="All"](https://github.com/OmniSharp/csharp-language-server-protocol/blob/ab6e519ce22104a2f7f9c8573b0d14671b020608/src/JsonRpc/JsonRpc.csproj#L19).

**Comment by chrissimon-au** [comment]
The initial exception can be resolved by marking `OmniSharp.Extensions.JsonRpc` as a TrimmerRoot, however new exceptions arise.  From running the test suite against the build trimmed binary, determined the following assemblies must be marked as TrimmerRoots, mostly due to the extensive use of reflection by OmniSharp :

```
    <TrimmerRootAssembly Include="OmniSharp.Extensions.JsonRpc" />
    <TrimmerRootAssembly Include="OmniSharp.Extensions.LanguageServer" />
    <TrimmerRootAssembly Include="OmniSharp.Extensions.LanguageProtocol" />
    <TrimmerRootAssembly Include="OmniSharp.Extensions.LanguageServer.Shared" />
    <TrimmerRootAssembly Include="Newtonsoft.Json" />
    <TrimmerRootAssembly Include="MediatR" />
    <TrimmerRootAssembly Include="Contextive.Core" />
```

The impact on file sizes is:

```
v1.10.3        (net6.0): trimMode partial (default)      : 56.0 MB
v1.10.4        (net7.0): trimMode full (default), broken : 49.0 MB
v1.10.5        (net7.0): no trimming, short term fix     : 78.6 MB
v1.10.5.bugfix (net7.0): trimMode partial                : 65.4 MB
v1.10.5.bugfix (net7.0): trimMode full with roots        : 55.5 MB
```

It seems the safest option would be to deploy with TrimMode partial - resulting in a filesize increase from 56MB to 65.4MB as a result of moving from .NET 6 to .NET 7.

However, with trimMode full but explicitly nominating the required trimmerRoots, we actually have a smaller file size (55.5MB), but the increased risk of a new assembly causing an issue.  To mitigate this risk, propose updating the vscode e2e tests in the CI workflow to use the published/trimmed binary instead of `dotnet run` debug mode.

A preliminary step will attempt to run the language server immediately (with a 2s timeout, as it doesn't end on it's own).  This will  make any trimmer-caused exceptions that prevent startup extremely obvious. Other issues will get caught by the vscode e2e tests.
