### ISSUE TITLE
IntelliJ: UnsatisfiedLinkError

### ISSUE THREAD

**Issue by schaarda** [dev-cycles/contextive#86]
**Describe the bug**
Right after opening a file (e.g. a definitions.yml itself) I get the following error:

> java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
	at com.sun.jna.platform.win32.Shell32.<clinit>(Shell32.java:48)
	at com.sun.jna.platform.win32.Shell32Util.getFolderPath(Shell32Util.java:55)
	at com.sun.jna.platform.win32.Shell32Util.getFolderPath(Shell32Util.java:71)
	at net.harawata.appdirs.impl.ShellFolderResolver.resolveFolder(ShellFolderResolver.java:38)
	at net.harawata.appdirs.impl.WindowsAppDirs.getLocalAppData(WindowsAppDirs.java:81)
	at net.harawata.appdirs.impl.WindowsAppDirs.getUserDataDir(WindowsAppDirs.java:33)
	at net.harawata.appdirs.AppDirs.getUserDataDir(AppDirs.java:20)
	at tech.contextive.contextive.LanguageServerLocationResolver.path(LanguageServerLocationResolver.kt:47)
	at tech.contextive.contextive.LanguageServerDownloadScheduler.scheduleDownloadIfRequired(LanguageServerDownloadScheduler.kt:40)
	at tech.contextive.contextive.ContextiveManager.startIfRequired(ContextiveManager.kt:20)
	at tech.contextive.contextive.ContextiveLspServerSupportProvider.fileOpened(ContextiveLspServerSupportProvider.kt:22)
	at com.intellij.platform.lsp.impl.LspOpenedFilesService.G(LspOpenedFilesService.kt:80)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor.callWrapped(NonBlockingReadActionImpl.java:840)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor$MonitoredComputation.call(NonBlockingReadActionImpl.java:872)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:604)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$4(NonBlockingReadActionImpl.java:567)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:291)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:93)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:155)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:138)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:217)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:98)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:135)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:93)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:567)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:466)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$2(NonBlockingReadActionImpl.java:481)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Unable to locate JNA native support library [in thread "ApplicationImpl pooled thread 6"]
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:1018)
	at com.sun.jna.Native.<clinit>(Native.java:221)
	at com.sun.jna.Structure.setAlignType(Structure.java:291)
	at com.sun.jna.Structure.<init>(Structure.java:208)
	at com.sun.jna.Structure.<init>(Structure.java:204)
	at com.sun.jna.Structure.<init>(Structure.java:191)
	at com.sun.jna.Structure.<init>(Structure.java:183)
	at com.sun.jna.platform.win32.Guid$GUID.<init>(Guid.java:126)
	at com.sun.jna.platform.win32.Guid$GUID.fromString(Guid.java:257)
	at com.sun.jna.platform.win32.KnownFolders.<clinit>(KnownFolders.java:41)
	at net.harawata.appdirs.impl.ShellFolderResolver.convertFolderIdToGuid(ShellFolderResolver.java:51)
	at net.harawata.appdirs.impl.ShellFolderResolver.resolveFolder(ShellFolderResolver.java:30)
	... 39 more

Context-Information on Mouse-Over is not shown, no auto-completion, the plugin does not seem to work at all.

**To Reproduce**
1. open definitions.yml
2. See error

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version IntelliJ Idea Ultimate 2024.2.4
 -- JVM-Runtime version: 21.0.4+13-b509.26 amd64,  OpenJDK 64-Bit Server VM by JetBrains s.r.o.
 --  Contextive 1.12.1

**Comment by chrissimon-au** [comment]
Hi @schaarda,

Thanks for reporting this - from the exception details and your desktop configuration, this appears to be an error in some code that is attempting to adapt to windows specific folder conventions used for determining where to look for (and download to) the language server.

Things are definitely working fine with that combination of IntelliJ and Contextive on other platforms, so let me take a look at things on a windows platform and see if I can replicate.
